spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/assessment_min
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 12345678

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:pre_query.sql, classpath:mariadb_ddl.sql, classpath:mariadb_dml.sql

logging:
  level:
    root: info